version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

  backend:
    build: ./dtest-backend
    env_file:
      - ./dtest-backend/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - mailhog

  frontend:
    build: ./dtest-frontend/app
    ports:
      - '3000:3000'
    depends_on:
      - backend

  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
